spring:
  application:
    name: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  healthcheck:
    enabled: true

server:
  port: 8084
 
zuul:
  routes:
    UserInfoService:
      path: /user/**                                
      url: http://localhost:8081/user 
    BookInfoService:
      path: /book/**                                
      url: http://localhost:8082/book
    BooksCatalogueService:
      path: /catalog/**                                
      url: http://localhost:8083/catalog 